name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set target to Windows
        run: rustup set default-host x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
